"""add expense fields

Revision ID: 9ee19dbda1cb
Revises: 075c477d839b
Create Date: 2026-02-24 11:52:06.244125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9ee19dbda1cb'
down_revision = '075c477d839b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deliverers_employee_id', table_name='deliverers')
    op.drop_index('ix_deliverers_id', table_name='deliverers')
    op.drop_index('ix_deliverers_is_available', table_name='deliverers')
    op.drop_index('ix_deliverers_territory', table_name='deliverers')
    op.drop_table('deliverers')
    op.drop_index('ix_inventory_transactions_id', table_name='inventory_transactions')
    op.drop_index('ix_inventory_transactions_inventory_id', table_name='inventory_transactions')
    op.drop_index('ix_inventory_transactions_product_id', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index('ix_resellers_id', table_name='resellers')
    op.drop_index('ix_resellers_is_active', table_name='resellers')
    op.drop_table('resellers')
    op.drop_index('ix_suppliers_id', table_name='suppliers')
    op.drop_index('ix_suppliers_is_active', table_name='suppliers')
    op.drop_index('ix_suppliers_name', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_clients_id', table_name='clients')
    op.drop_index('ix_clients_is_active', table_name='clients')
    op.drop_index('ix_clients_name', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_order_items_id', table_name='order_items')
    op.drop_index('ix_order_items_product_id', table_name='order_items')
    op.drop_index('ix_order_items_supplier_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_expenses_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_supplier_orders_id', table_name='supplier_orders')
    op.drop_index('ix_supplier_orders_order_number', table_name='supplier_orders')
    op.drop_index('ix_supplier_orders_supplier_id', table_name='supplier_orders')
    op.drop_table('supplier_orders')
    op.drop_index('ix_routes_id', table_name='routes')
    op.drop_table('routes')
    op.drop_index('ix_supplier_products_id', table_name='supplier_products')
    op.drop_index('ix_supplier_products_product_id', table_name='supplier_products')
    op.drop_index('ix_supplier_products_supplier_id', table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index('ix_inventories_id', table_name='inventories')
    op.drop_index('ix_inventories_is_active', table_name='inventories')
    op.drop_index('ix_inventories_product_id', table_name='inventories')
    op.drop_table('inventories')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_index('ix_orders_reseller_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_is_active', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('size', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sku', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reseller_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index('ix_orders_reseller_id', 'orders', ['reseller_id'], unique=False)
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('reserved', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('min_stock', sa.INTEGER(), nullable=True),
    sa.Column('max_stock', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventories_product_id', 'inventories', ['product_id'], unique=False)
    op.create_index('ix_inventories_is_active', 'inventories', ['is_active'], unique=False)
    op.create_index('ix_inventories_id', 'inventories', ['id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('supplier_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('supplier_sku', sa.VARCHAR(length=100), nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('min_quantity', sa.INTEGER(), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_products_supplier_id', 'supplier_products', ['supplier_id'], unique=False)
    op.create_index('ix_supplier_products_product_id', 'supplier_products', ['product_id'], unique=False)
    op.create_index('ix_supplier_products_id', 'supplier_products', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('route_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routes_id', 'routes', ['id'], unique=False)
    op.create_table('supplier_orders',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('supplier_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('expected_delivery', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_orders_supplier_id', 'supplier_orders', ['supplier_id'], unique=False)
    op.create_index('ix_supplier_orders_order_number', 'supplier_orders', ['order_number'], unique=False)
    op.create_index('ix_supplier_orders_id', 'supplier_orders', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_id', 'expenses', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('supplier_order_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_order_id'], ['supplier_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_supplier_order_id', 'order_items', ['supplier_order_id'], unique=False)
    op.create_index('ix_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('ix_order_items_id', 'order_items', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), nullable=True),
    sa.Column('client_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('payment_terms', sa.VARCHAR(length=20), nullable=True),
    sa.Column('credit_limit', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('outstanding_balance', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_name', 'clients', ['name'], unique=False)
    op.create_index('ix_clients_is_active', 'clients', ['is_active'], unique=False)
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_name', 'suppliers', ['name'], unique=False)
    op.create_index('ix_suppliers_is_active', 'suppliers', ['is_active'], unique=False)
    op.create_index('ix_suppliers_id', 'suppliers', ['id'], unique=False)
    op.create_table('resellers',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resellers_is_active', 'resellers', ['is_active'], unique=False)
    op.create_index('ix_resellers_id', 'resellers', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inventory_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('product_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('change', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_transactions_product_id', 'inventory_transactions', ['product_id'], unique=False)
    op.create_index('ix_inventory_transactions_inventory_id', 'inventory_transactions', ['inventory_id'], unique=False)
    op.create_index('ix_inventory_transactions_id', 'inventory_transactions', ['id'], unique=False)
    op.create_table('deliverers',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('vehicle_info', sqlite.JSON(), nullable=True),
    sa.Column('license_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('hire_date', sa.DATE(), nullable=True),
    sa.Column('territory', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.Column('current_location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_location_update', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliverers_territory', 'deliverers', ['territory'], unique=False)
    op.create_index('ix_deliverers_is_available', 'deliverers', ['is_available'], unique=False)
    op.create_index('ix_deliverers_id', 'deliverers', ['id'], unique=False)
    op.create_index('ix_deliverers_employee_id', 'deliverers', ['employee_id'], unique=False)
    # ### end Alembic commands ###